from __future__ import annotations

from typing import Any

from rai_audit.core.findings import AuditFinding, AuditReport, RiskLevel, Severity
from rai_audit.core.standards import describe_refs

_RISK_COLOR = {
    RiskLevel.CRITICAL: "#c0392b",
    RiskLevel.HIGH: "#e67e22",
    RiskLevel.MEDIUM: "#f1c40f",
    RiskLevel.LOW: "#27ae60",
}

_SEVERITY_COLOR = {
    Severity.CRITICAL: "#c0392b",
    Severity.HIGH: "#e67e22",
    Severity.MEDIUM: "#f39c12",
    Severity.LOW: "#3498db",
    Severity.INFO: "#95a5a6",
    Severity.PASSED: "#27ae60",
}

_SEVERITY_BADGE_BG = {
    Severity.CRITICAL: "#fdecea",
    Severity.HIGH: "#fef3e7",
    Severity.MEDIUM: "#fefce7",
    Severity.LOW: "#eaf4fb",
    Severity.INFO: "#f4f4f4",
    Severity.PASSED: "#eafaf1",
}


# ── Markdown ──────────────────────────────────────────────────────────────────

def render_markdown(report: AuditReport) -> str:
    lines: list[str] = []

    lines.append(f"# Audit Report: {report.project_name}")
    lines.append(f"\n**Audit type:** {report.audit_type}")
    lines.append(f"**Overall risk:** {report.overall_risk_level.value.upper()}")
    if report.overall_score is not None:
        lines.append(f"**Score (heuristic):** {report.overall_score:.1f}/100")

    lines.append("\n## Risk Summary\n")
    lines.append("| Category | Risk Level | Findings | Passed |")
    lines.append("|----------|-----------|----------|--------|")
    for cat in report.risk_matrix:
        lines.append(
            f"| {cat.category} | {cat.risk_level.value.upper()} "
            f"| {cat.finding_count} | {cat.passed_count} |"
        )

    active = [f for f in report.findings if f.severity != Severity.PASSED]
    passed = [f for f in report.findings if f.severity == Severity.PASSED]

    if active:
        lines.append("\n## Findings\n")
        for f in active:
            lines.append(f"### [{f.severity.value.upper()}] {f.title}")
            lines.append(f"\n**Check:** `{f.check_id}`  ")
            lines.append(f"**Category:** {f.category}  ")
            if f.affected_group:
                lines.append(f"**Affected group:** {f.affected_group}  ")
            lines.append(f"**Remediation effort:** {f.remediation_effort.value}  ")
            lines.append(f"\n{f.description}")
            if f.evidence:
                lines.append("\n**Evidence:**")
                for k, v in f.evidence.items():
                    lines.append(f"- `{k}`: {v}")
            lines.append(f"\n**Recommendation:** {f.recommendation}")
            if f.standards_refs:
                lines.append("\n**Standards:**")
                for ref in describe_refs(f.standards_refs):
                    lines.append(f"- {ref}")
            lines.append("")

    if passed:
        lines.append(f"\n## Passed Checks ({len(passed)})\n")
        for f in passed:
            lines.append(f"- ✓ `{f.check_id}` — {f.title}")

    lines.append(f"\n---\n*Generated by rai-check-core*")
    return "\n".join(lines)


# ── HTML ──────────────────────────────────────────────────────────────────────

def render_html(report: AuditReport) -> str:
    active = [f for f in report.findings if f.severity != Severity.PASSED]
    passed = [f for f in report.findings if f.severity == Severity.PASSED]
    overall_color = _RISK_COLOR.get(report.overall_risk_level, "#95a5a6")

    risk_rows = "".join(
        f"""<tr>
          <td>{cat.category}</td>
          <td><span style="color:{_RISK_COLOR.get(cat.risk_level,'#333')};font-weight:600">
            {cat.risk_level.value.upper()}</span></td>
          <td>{cat.finding_count}</td>
          <td>{cat.passed_count}</td>
        </tr>"""
        for cat in report.risk_matrix
    )

    finding_cards = "".join(_finding_card(f) for f in active)

    passed_list = "".join(
        f'<li><code>{f.check_id}</code> — {f.title}</li>' for f in passed
    )

    score_html = ""
    if report.overall_score is not None:
        score_html = (
            f'<p style="color:#888;font-size:0.85em">'
            f'Heuristic score: {report.overall_score:.1f}/100 '
            f'(not a substitute for reviewing individual findings)</p>'
        )

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Audit Report — {_esc(report.project_name)}</title>
<style>
  *, *::before, *::after {{ box-sizing: border-box; }}
  body {{ font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
         margin: 0; background: #f7f8fa; color: #1a1a2e; line-height: 1.6; }}
  .container {{ max-width: 960px; margin: 0 auto; padding: 2rem 1.5rem; }}
  h1 {{ font-size: 1.8rem; margin-bottom: 0.25rem; }}
  h2 {{ font-size: 1.25rem; margin-top: 2rem; border-bottom: 2px solid #e8eaf0;
       padding-bottom: 0.4rem; }}
  .meta {{ color: #555; font-size: 0.92rem; margin-bottom: 1.5rem; }}
  .risk-badge {{ display: inline-block; padding: 0.25rem 0.75rem; border-radius: 4px;
                font-weight: 700; font-size: 0.9rem; color: #fff;
                background: {overall_color}; }}
  table {{ width: 100%; border-collapse: collapse; margin-top: 0.75rem; }}
  th {{ background: #f0f2f7; text-align: left; padding: 0.6rem 0.75rem;
       font-size: 0.85rem; text-transform: uppercase; letter-spacing: 0.04em; }}
  td {{ padding: 0.55rem 0.75rem; border-bottom: 1px solid #e8eaf0; font-size: 0.92rem; }}
  tr:last-child td {{ border-bottom: none; }}
  .card {{ background: #fff; border: 1px solid #e8eaf0; border-radius: 8px;
           padding: 1.25rem 1.5rem; margin-bottom: 1rem;
           border-left: 4px solid #ccc; }}
  .card-title {{ font-size: 1rem; font-weight: 600; margin: 0 0 0.5rem; }}
  .card-meta {{ font-size: 0.82rem; color: #666; margin-bottom: 0.75rem; }}
  .card-meta span {{ margin-right: 1rem; }}
  .sev-badge {{ display: inline-block; padding: 0.15rem 0.5rem; border-radius: 3px;
               font-weight: 700; font-size: 0.78rem; text-transform: uppercase; }}
  .evidence {{ background: #f7f8fa; border-radius: 4px; padding: 0.6rem 0.9rem;
              font-size: 0.85rem; margin: 0.5rem 0; }}
  .evidence code {{ font-family: monospace; }}
  .rec {{ border-top: 1px solid #e8eaf0; margin-top: 0.75rem; padding-top: 0.75rem;
          font-size: 0.9rem; }}
  .standards {{ font-size: 0.8rem; color: #555; margin-top: 0.4rem; }}
  .passed-list {{ list-style: none; padding: 0; columns: 2; gap: 1rem; }}
  .passed-list li {{ padding: 0.3rem 0; font-size: 0.88rem; color: #2ecc71; }}
  .passed-list li::before {{ content: "✓ "; font-weight: 700; }}
  footer {{ text-align: center; color: #aaa; font-size: 0.8rem; margin-top: 3rem; }}
</style>
</head>
<body>
<div class="container">
  <h1>{_esc(report.project_name)}</h1>
  <div class="meta">
    <strong>Audit type:</strong> {_esc(report.audit_type)} &nbsp;|&nbsp;
    <strong>Overall risk:</strong> <span class="risk-badge">{report.overall_risk_level.value.upper()}</span>
    &nbsp;|&nbsp; <strong>Findings:</strong> {len(active)}
    &nbsp;|&nbsp; <strong>Passed:</strong> {len(passed)}
  </div>
  {score_html}

  <h2>Risk Summary</h2>
  <table>
    <thead><tr><th>Category</th><th>Risk Level</th><th>Findings</th><th>Passed</th></tr></thead>
    <tbody>{risk_rows}</tbody>
  </table>
  {_risk_chart_svg(report)}

  {"<h2>Findings</h2>" + finding_cards if active else ""}

  {"<h2>Passed Checks (" + str(len(passed)) + ")</h2><ul class='passed-list'>" + passed_list + "</ul>" if passed else ""}

  <footer>Generated by <strong>rai-check-core</strong></footer>
</div>
</body>
</html>"""


def _finding_card(f: AuditFinding) -> str:
    border_color = _SEVERITY_COLOR.get(f.severity, "#ccc")
    badge_bg = _SEVERITY_BADGE_BG.get(f.severity, "#eee")
    badge_color = _SEVERITY_COLOR.get(f.severity, "#333")

    evidence_html = ""
    if f.evidence:
        scalar_rows = "".join(
            f"<tr><td><code>{_esc(str(k))}</code></td><td>{_esc(str(v))}</td></tr>"
            for k, v in f.evidence.items()
            if not isinstance(v, (dict, list))
        )
        scalar_table = (
            f'<div class="evidence"><table style="width:100%;font-size:0.85rem">'
            f"<tbody>{scalar_rows}</tbody></table></div>"
            if scalar_rows
            else ""
        )
        group_tables = _group_tables_html(f.evidence)
        group_section = (
            f'<div class="evidence">{group_tables}</div>' if group_tables else ""
        )
        evidence_html = scalar_table + group_section

    group_html = (
        f'<span>Group: <strong>{_esc(f.affected_group)}</strong></span>'
        if f.affected_group
        else ""
    )

    standards_html = ""
    if f.standards_refs:
        refs = ", ".join(f.standards_refs)
        standards_html = f'<div class="standards">Standards: {_esc(refs)}</div>'

    return f"""<div class="card" style="border-left-color:{border_color}">
  <div class="card-title">
    <span class="sev-badge" style="background:{badge_bg};color:{badge_color}">
      {f.severity.value.upper()}</span>&nbsp; {_esc(f.title)}
  </div>
  <div class="card-meta">
    <span>Check: <code>{_esc(f.check_id)}</code></span>
    <span>Category: {_esc(f.category)}</span>
    {group_html}
    <span>Effort: {f.remediation_effort.value}</span>
  </div>
  <p style="margin:0.25rem 0">{_esc(f.description)}</p>
  {evidence_html}
  <div class="rec"><strong>Recommendation:</strong> {_esc(f.recommendation)}</div>
  {standards_html}
</div>"""


def _esc(text: str) -> str:
    return (
        str(text)
        .replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
    )


def _risk_chart_svg(report: AuditReport) -> str:
    """Inline SVG bar chart — active findings per category, colored by risk level."""
    cats = report.risk_matrix
    if not cats:
        return ""

    bar_w = 60
    gap = 18
    pad_left = 42
    pad_top = 32
    chart_h = 140
    label_h = 48
    chart_w = pad_left + len(cats) * (bar_w + gap) + gap
    total_h = pad_top + chart_h + label_h

    max_count = max((c.finding_count for c in cats), default=0) or 1

    elems: list[str] = []

    # Axes
    elems.append(
        f'<line x1="{pad_left}" y1="{pad_top}" x2="{pad_left}" '
        f'y2="{pad_top + chart_h}" stroke="#ccc" stroke-width="1"/>'
    )
    elems.append(
        f'<line x1="{pad_left}" y1="{pad_top + chart_h}" '
        f'x2="{chart_w - gap}" y2="{pad_top + chart_h}" stroke="#ccc" stroke-width="1"/>'
    )
    elems.append(
        f'<text x="{pad_left - 5}" y="{pad_top + chart_h + 3}" '
        f'text-anchor="end" font-size="10" fill="#888">0</text>'
    )
    elems.append(
        f'<text x="{pad_left - 5}" y="{pad_top + 5}" '
        f'text-anchor="end" font-size="10" fill="#888">{max_count}</text>'
    )

    for i, cat in enumerate(cats):
        x = pad_left + gap + i * (bar_w + gap)
        active_h = int((cat.finding_count / max_count) * (chart_h - 12)) if cat.finding_count else 0
        active_h = max(active_h, 3) if cat.finding_count else 0
        y = pad_top + chart_h - active_h
        color = _RISK_COLOR.get(cat.risk_level, "#95a5a6")

        elems.append(
            f'<rect x="{x}" y="{y}" width="{bar_w}" height="{active_h}" '
            f'fill="{color}" rx="3" opacity="0.85"/>'
        )
        if cat.finding_count:
            elems.append(
                f'<text x="{x + bar_w // 2}" y="{y - 4}" text-anchor="middle" '
                f'font-size="11" font-weight="600" fill="#333">{cat.finding_count}</text>'
            )
        short = cat.category[:10]
        elems.append(
            f'<text x="{x + bar_w // 2}" y="{pad_top + chart_h + 17}" '
            f'text-anchor="middle" font-size="10" fill="#555">{_esc(short)}</text>'
        )
        elems.append(
            f'<text x="{x + bar_w // 2}" y="{pad_top + chart_h + 33}" '
            f'text-anchor="middle" font-size="9" font-weight="600" fill="{color}">'
            f'{cat.risk_level.value.upper()}</text>'
        )

    elems.append(
        f'<text x="{chart_w // 2}" y="18" text-anchor="middle" '
        f'font-size="13" font-weight="600" fill="#333">Active Findings by Category</text>'
    )

    inner = "\n  ".join(elems)
    return (
        f'<svg viewBox="0 0 {chart_w} {total_h}" '
        f'style="width:100%;max-width:{chart_w}px;height:{total_h}px;display:block;margin:0.5rem 0">'
        f"\n  {inner}\n</svg>"
    )


def _group_tables_html(evidence: dict[str, Any]) -> str:
    """Render dict-valued evidence entries as compact group-metric tables."""
    parts: list[str] = []
    for k, v in evidence.items():
        if isinstance(v, dict) and v:
            label = k.replace("_", " ").title()
            rows = "".join(
                f"<tr>"
                f"<td style='padding:0.25rem 0.5rem'><strong>{_esc(str(gk))}</strong></td>"
                f"<td style='padding:0.25rem 0.5rem;text-align:right'>{_esc(str(gv))}</td>"
                f"</tr>"
                for gk, gv in v.items()
            )
            parts.append(
                f'<p style="font-size:0.82rem;font-weight:600;color:#555;margin:0.6rem 0 0.2rem">'
                f"{_esc(label)}</p>"
                f'<table style="border-collapse:collapse;font-size:0.83rem;min-width:180px">'
                f'<thead><tr>'
                f'<th style="text-align:left;padding:0.2rem 0.5rem;background:#f0f2f7;'
                f'font-size:0.78rem">Group</th>'
                f'<th style="text-align:right;padding:0.2rem 0.5rem;background:#f0f2f7;'
                f'font-size:0.78rem">Value</th>'
                f"</tr></thead>"
                f"<tbody>{rows}</tbody></table>"
            )
    return "\n".join(parts)
